SELECT
    H.FLAVOR
FROM
    FIRST_HALF AS H
JOIN
    ICECREAM_INFO AS INFO
ON
    H.FLAVOR = INFO.FLAVOR
WHERE
    H.TOTAL_ORDER > 3000 AND INFO.INGREDIENT_TYPE = 'fruit_based'
ORDER BY
    H.TOTAL_ORDER DESC;